# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*
    - README.md

name: '1.1.$(Rev:r)'

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build -c $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration)'

- task: DockerCompose@0
  displayName: Start RabbitMQ
  inputs:
    action: 'Run services'
    dockerComposeFile: docker-compose.yml
    projectName: $(Build.Repository.Name)
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'DockerHub'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test -c $(buildConfiguration) --no-build'
  inputs:
    command: 'test'
    arguments: '-c $(buildConfiguration) --no-build'

- task: DockerCompose@0
  displayName: Stop RabbitMQ
  condition: always()
  inputs:
    action: Run a Docker Compose command
    dockerComposeFile: docker-compose.yml
    projectName: $(Build.Repository.Name)
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'DockerHub'
    dockerComposeCommand: down

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack -c $(buildConfiguration) --no-build --include-symbols'
  inputs:
    command: 'custom'
    custom: 'pack'
    arguments: '-c $(buildConfiguration) --no-build --include-symbols --output $(build.artifactStagingDirectory) /p:PackageVersion=$(build.buildNumber)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'packages' 